### ISSUE TITLE
Website change feedback

### ISSUE THREAD

**Issue by shoeper** [FRRouting/frr-www#18]
The new website (introduced with #17 I think) is much worse than the old one imho (https://web.archive.org/web/20210313233622/https://frrouting.org/).

Especially for new people the old website was much more straight forward. It had immediately reachable and easy to find links to all important places of the project.

**Comment by wesleycoakley** [comment]
I agree there should be more useful, easily-accessible content on the frontpage. With #17 the focus was to rework the site to be more far, far easier to edit than the old one, since we now use Hugo to template the site instead of needing to write raw HTML.

The old site had a mile of release notes on the front page, followed finally by the hyperlinks out to different resources. I've tried organizing things better (e.g. grouping community resources together, hrefs out to documentation together) but obviously this detracts from the "immediate reachability" of everything. One open conversation is possibly moving the block of contributors on the homepage to their own corner of the site.

I'm unsure what content then could go on the frontpage. Many open-source projects ([gRPC](https://grpc.io/) [ZeroMQ](https://zeromq.org/), [Apache Kafka](https://kafka.apache.org/)) have short and sweet homepages that summarize key points of the project, our old site was out-of-place among these.

**Comment by qlyoung** [comment]
> It had immediately reachable and easy to find links to all important places of the project.

Let's look at the first screenful of the old website:
![2021-08-02-120923_2534x1164_scrot](https://user-images.githubusercontent.com/6827003/127891599-4974a0ed-68cc-44bc-9672-6a049e4a428e.png)

Two content anchors that jump to points further than halfway down the same page. Note that in the new site both of these links still exist, except now they go to the actual resources instead of anchors to the sections that the resources are contained in.

The next screenful is the list of release notes.

![2021-08-02-121541_2467x1246_scrot](https://user-images.githubusercontent.com/6827003/127892394-6fdee7d0-499c-4ad4-8c61-87cb98966109.png)


The next screenful is still the release notes.
![2021-08-02-121550_2482x1264_scrot](https://user-images.githubusercontent.com/6827003/127892412-848d667c-d584-4c9a-8fea-c23cbb0e4d3c.png)


The next screenful is still the release notes.
![2021-08-02-121602_2525x1262_scrot](https://user-images.githubusercontent.com/6827003/127892445-2aa6f016-641d-46ca-a125-bee74c8b3a73.png)


The next screenful finally has some useful content. I've put colored boxes around it to demonstrate where that same content now lives on the new website.
![2021-08-02-121708_2533x1265_scrot](https://user-images.githubusercontent.com/6827003/127894344-84a751ea-0a8c-491c-9a0a-370752187bd9.png)

New website, with mapping from the 4th screenful from the old website:
![2021-08-02-121002_2538x1247_scrot](https://user-images.githubusercontent.com/6827003/127894476-b7a2e280-40e0-47f2-9d46-ee94e4c55cb1.png)

Notice how everything is now on the first page. This alone is a massive improvement.

As for new users, the new user cares about two things:
1. How do I install the software?
2. How do I get help?

Both of these are prominently featured - "Releases" and "Community" - just as they were on the old site.

To me this is way better than the old website. Now if you have feedback for how the content is organized under the header sections, I would like to hear that as I'm not sure we have the best setup there.

As to Wesley's point, the current site is infinitely easier for us - the people who write it - to work on and maintain, so internally this is a massive win for us also.
